# Generated by Django 4.2.3 on 2023-07-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Demographic', models.CharField(choices=[('Teens', 'Teens'), ('Children', 'Children'), ('Adults', 'Adults')], max_length=100)),
                ('Gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('All', 'All'), ('Men', 'Men'), ('Women', 'Women')], max_length=100)),
                ('Description', models.TextField(max_length=250)),
            ],
        ),
    ]
