# Generated by Django 4.2.3 on 2023-07-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beater', models.CharField(choices=[('P', 'Porky'), ('C', 'Charcoal'), ('Z', 'Zephyr'), ('TJ', 'Therapist Joe'), ('KM', 'Krombopulos Michael'), ('PR', 'Period')], max_length=2)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bta_app.beat')),
            ],
        ),
    ]
